server:
  port: 8080
  servlet:
    context-path: /redis-lock-example

spring:
  jackson:
    property-naming-strategy: com.fasterxml.jackson.databind.PropertyNamingStrategies.SnakeCaseStrategy
  datasource:
    db: redis_lock_db
    host: localhost
    port: 5432
    default-schema: redis_lock
    url: "jdbc:postgresql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.db}?currentSchema=${spring.datasource.default-schema}"
    username: redis_lock
    password: redis_lock
  flyway:
    schemas: ${spring.datasource.default-schema}
  data:
    redis:
      port: 6379
      host: localhost

redis-lock-example:
  lock-registry-key: job_lock
  release-time-duration: 30